# Use una imagen base de Node.js adecuada para tu proyecto
FROM node:latest

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /ChampionsTracker/ChampionsTracker-Frontend

# Copia solo el archivo package.json primero
COPY package.json .

# Instala las dependencias, incluyendo esbuild (o las necesarias)
RUN npm install esbuild

# Copia el resto de los archivos
COPY . .

# Exponer el puerto en el que la aplicación se ejecuta
EXPOSE 5173

# Comando para ejecutar la aplicación React
CMD ["npm", "run", "dev"]
